from apispec import APISpec
import yaml 
from typing import Dict, Any
import re 

def build_openapi(agent_output: Dict[str, Any], title: str = "Generated API", version: str= "1.0.0") -> Dict:
    spec = APISpec(
        title=title,
        version=version,
        openapi_version="3.0.3",
        info={"description": "API generated by Ai assistant"},
        plugins=[] )
    
    schemas=agent_output.get("schemas", {})
    if schemas:
        spec.components.schema("GeneratedSchemas",schema={})
        pass 

    spec_dict={ 
        "openapi": "3.0.3",
        "info":{"title": title, "version":version,"description":"API generated by Ai assistant"},
        "paths":{},
        "components":{"schemas":{}}
    }

    for name, schema in agent_output.get("schemas",{}).items():
        spec_dict["components"]["schemas"][name]=schema

    for e in agent_output.get("endpoints", []):
            path = e["path"]
            method = e["method"].lower()

            # Ensure path entry exists
            if path not in spec_dict["paths"]:
                spec_dict["paths"][path] = {}

            # --- Build operation object for this method ---
            op = {
                "summary": e.get("description", ""),
                "responses": {}
            }

            # --- Auto-generate path parameters from /foo/{bar}/baz ---
            param_names = re.findall(r"{([^}]+)}", path)
            if param_names:
                op["parameters"] = []
                for name in param_names:
                    op["parameters"].append(
                        {
                            "name": name,
                            "in": "path",
                            "required": True,
                            "schema": {"type": "string"},
                        }
                    )

            # --- Responses ---
            for status, desc in (e.get("responses") or {}).items():
                # If the LLM gave a schema-like object (dict), wrap it as a proper response
                if isinstance(desc, dict):
                    op["responses"][str(status)] = {
                        "description": "Success" if str(status).startswith("2") else "Response",
                        "content": {
                            "application/json": {
                                "schema": desc
                            }
                        }
                    }
                else:
                    # Plain string description
                    op["responses"][str(status)] = {
                        "description": desc
                    }

            # --- Request body (if any) ---
            if e.get("requestBody"):
                op["requestBody"] = {
                    "content": {
                        "application/json": {
                            "schema": e["requestBody"]
                        }
                    }
                }

            # Attach operation to path + method
            spec_dict["paths"][path][method] = op


    return spec_dict

def save_spec_yaml(spec_dict:Dict, out_path:str):
    with open(out_path,"w") as f:
        yaml.safe_dump(spec_dict, f, sort_keys=False)